version: 2
jobs:
  build:
    working_directory: ~/Android/Workspace/Quora

    docker:
      - image: circleci/android:api-25-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "quora/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "quora/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
          command: ./gradlew pmd test
          command: ./gradlew findBugs test
          command: ./gradlew assembleDebug
          command: ./gradlew test
      - store_artifacts:
          path: quora/build/reports/
          destination: reports
      - store_test_results:
          path: quora/build/reports/test_results